/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://epuod55nifb2hlk6qfmh4q7b7y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fx5uzoskdnfrpbggymlq5gj7wu",
    "aws_cognito_identity_pool_id": "us-east-1:6e66ea22-9242-433b-970d-14333ef3f3d7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UDQxPwHzL",
    "aws_user_pools_web_client_id": "28d1k4lmuisu8uhel8hnlovv5k",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
